In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics.pairwise import linear_kernel
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk.stem.wordnet import WordNetLemmatizer
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk.tokenize import RegexpTokenizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


In [13]:
import pickle

In [2]:
df2=pd.read_csv("df_CA_Summarization_filtered.csv")

In [ ]:
df2.head()

Unnamed: 0  Unnamed: 0.1  \
0           0             0   
1           2             3   
2           3             7   
3           5            16   
4           6            18   

                                           education   gPlusUserId  \
0  [['[]'; '[]'; '[]'; '[]'; '[]'; '6']; ['["The ...  1.002152e+20   
1  [['[]'; '[]'; '[]'; '[]'; '[]'; '6']; ['["Univ...  1.019804e+20   
2  [['[]'; '[]'; '[]'; '[]'; '[]'; '6']; ['["Univ...  1.029165e+20   
3  [['[]'; '[]'; '[]'; '[]'; '[]'; '6']; ['["Texa...  1.060633e+20   
4          [['[]'; '[]'; '[]'; '[]'; '[]'; '6']; []]  1.074869e+20   

                                            address  closed  \
0     ['546 University Ave'; 'Palo Alto; CA 94301']   False   
1  ['655 Divisadero St'; 'San Francisco; CA 94117']   False   
2        ['355 11th St'; 'San Francisco; CA 94103']   False   
3     ['6530 Sunset Blvd'; 'Los Angeles; CA 90028']   False   
4     ['2298 Market St'; 'San Francisco; CA 94114']   False   

                        gps  \
0  [37.448889, -122.158481]   
1  [37.775721, -122.438054]   
2  [37.771291, -122.413113]   
3  [34.097787, -118.332712]   
4   [37.76459, -122.432918]   

                                               hours  \
0  [['Monday'; '[["11:30 am--2:30 pm"];["5:00--9:...   
1  [['Monday'; '[["Closed"]]'; '1']; ['Tuesday'; ...   
2  [['Monday'; '[["6:00--10:00 pm"]]'; '1']; ['Tu...   
3  [['Monday'; '[["11:30 am--10:30 pm"]]']; ['Tue...   
4  [['Monday'; '[["7:00 am--1:00 am"]]'; '1']; ['...   

                              name           phone  ...  \
0                         Tamarine  (650) 325-8500  ...   
1                        BAR CRUDO  (415) 409-0679  ...   
2                     Bar Agricole  (415) 355-9400  ...   
3  Cat and Fiddle Pub & Restaurant  (323) 468-3800  ...   
4                       Cafe Flore  (415) 621-8579  ...   

                                                jobs         loc  \
0  [['Google'; 'Engineer'; '[[];[1;1;2011];1]'; '...  California   
1  [['Retailigence'; 'Director of Business Develo...  California   
2  [['Farmer Brownstein Jaeger LLP'; 'Partner'; '...  California   
3  [["McDonald's"; 'Burger Bitch'; '[]'; 'http://...  California   
4  [['YouTube'; 'Web Developer'; '[[1;1;2011];[1;...  California   

                                      cleaned_review  \
0  bit expensive lunch specials reasonable excell...   
1  would normally consider foofoo based portion s...   
2   drinks outshine food great place amiable evening   
3  brings back time spent uk patio great atmosphe...   
4  standard goto meal anytime day great outdoor s...   

                                     cleaned_summary  \
0  bit expensive but lunch specials are reasonabl...   
1  the crudo is made up of pure deliciousness nei...   
2  drinks outshine the food here but great place ...   
3  the patio is great atmosphere don think would ...   
4  great outdoor seating supposedly they have fre...   

                                   cleaned_education  \
0              university minnesota computer science   
1     university missouri rolla computer engineering   
2  university california berkeley http www freeba...   
3    texas university http www freebase com view ccs   
4                                                NaN   

                              cleaned_address  \
0     546 university ave palo alto; ca 94301    
1  655 divisadero st san francisco; ca 94117    
2        355 11th st san francisco; ca 94103    
3     6530 sunset blvd los angeles; ca 90028    
4     2298 market st san francisco; ca 94114    

                                       cleaned_hours  \
0  monday 11:30 am; 2:30 pm ;5:00; 9:00 pm tuesda...   
1  monday closed tuesday 5:00; 10:00 pm wednesday...   
2  monday 6:00; 10:00 pm tuesday 6:00; 10:00 pm w...   
3  monday 11:30 am; 10:30 pm tuesday 11:30 am; 11...   
4  monday 7:00 am; 1:00 am tuesday 7:00 am; 1:00 ...   

                                  cleaned_categories  \
0  restaurant asian restauran

In [ ]:
mapping = pd.Series(df2.index,index = df2['name'])
mapping

name
Tamarine                               0
Blue Fig                               1
Umami Burger                           2
BAR CRUDO                              3
Southern Pacific Brewing               4
                                    ... 
Naja's Place                        2084
Crow's Nest Restaurant              2090
The Kitchen Restaurant              2209
Olive Cafe                          2647
Espana's Southwest Bar and Grill    2703
Length: 347, dtype: int64

In [ ]:
with open('mappingTable.pkl', 'wb') as file:
      
    # A new file will be created
    pickle.dump(mapping, file)

In [ ]:
type(mapping)

pandas.core.series.Series

In [ ]:
df2.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'education', 'gPlusUserId', 'address',
       'closed', 'gps', 'hours', 'name', 'phone', 'price', 'categories',
       'gPlusPlaceId', 'rating', 'reviewText', 'reviewCount', 'userCount',
       'jobs', 'loc', 'cleaned_review', 'cleaned_summary', 'cleaned_education',
       'cleaned_address', 'cleaned_hours', 'cleaned_categories',
       'cleaned_jobs', 'sentiment_VADER'],
      dtype='object')

In [ ]:
####### Recommendation without specific category
## Find the most preferred restaurant by person

#def pref_Rest (userID):
#  df1=pd.read_pickle('df1.pkl')
#  bestSent=df1.sort_values(['rating'],ascending=False).groupby(['gPlusUserId'],as_index=False)[['gPlusUserId','name','rating']].first()
#  restName=bestSent["name"].iloc[bestSent.index[bestSent["gPlusUserId"]== userID]].values[0]
#  return restName




In [ ]:
bestSent=df1.sort_values(['rating'],ascending=False).groupby(['gPlusUserId'],as_index=False)[['gPlusUserId','name','rating']].first()
restName=bestSent["name"].iloc[bestSent.index[bestSent["gPlusUserId"]== str(userID)]].values[0]

In [ ]:
df2.to_pickle("df1.pkl")

In [15]:
with open('mappingTable.pkl', 'rb') as file:
      
    # Call load method to deserialze
    mapping = pickle.load(file)
print(mapping)

name
Tamarine                               0
Blue Fig                               1
Umami Burger                           2
BAR CRUDO                              3
Southern Pacific Brewing               4
                                    ... 
Naja's Place                        2084
Crow's Nest Restaurant              2090
The Kitchen Restaurant              2209
Olive Cafe                          2647
Espana's Southwest Bar and Grill    2703
Length: 347, dtype: int64


In [ ]:
category_dummy =df2['categories'].str.join('|').str.get_dummies()
similarity_matrix = linear_kernel(category_dummy,category_dummy)
similarity_matrix

In [ ]:
np.save("similarity_matrix.npy",similarity_matrix)

In [10]:
similarity_matrix = np.load('similarity_matrix.npy')

In [11]:
print(similarity_matrix)

[[3. 1. 1. ... 1. 1. 1.]
 [1. 2. 1. ... 1. 2. 1.]
 [1. 1. 3. ... 1. 1. 2.]
 ...
 [1. 1. 1. ... 3. 1. 1.]
 [1. 2. 1. ... 1. 3. 1.]
 [1. 1. 2. ... 1. 1. 3.]]


In [15]:
def recommend_restaurant(userID=1.002151589e+20):
  df1=pd.read_csv('df_CA_Summarization_filtered.csv')
  with open('mappingTable.pkl', 'rb') as file:
      
    # Call load method to deserialze
    mapping = pickle.load(file)
  similarity_matrix = np.load('similarity_matrix.npy')
  bestSent=df1.sort_values(['rating'],ascending=False).groupby(['gPlusUserId'],as_index=False)[['gPlusUserId','name','sentiment_VADER']].first()
  restaurantChosen=bestSent["name"].iloc[bestSent.index[bestSent["gPlusUserId"]== userID]].values[0]
  restaurant_index = mapping[restaurantChosen]
  #get similarity values with other restaurants
  #similarity_score is the list of index and similarity matrix
  similarity_score = list(enumerate(similarity_matrix[restaurant_index]))
  #sort in descending order the similarity score of movie inputted with all the other movies
  similarity_score = sorted(similarity_score, key=lambda x: x[1], reverse=True)
  # Get the scores of the 15 most similar movies. Ignore the first movie.
  similarity_score = similarity_score[1:4]
  #return movie names using the mapping series
  restaurant_index = [i[0] for i in similarity_score]
  #return ("Top 3 restaurants: 1. "+str(df1['name'].iloc[restaurant_index].values[0])+" 2. "+str(df1['name'].iloc[restaurant_index].values[1])+" 3. "+str(df1['name'].iloc[restaurant_index].values[2]))
  return (pd.DataFrame({'Name':df1['name'].iloc[restaurant_index],'Categories':df1['categories'].iloc[restaurant_index]}))
